branches:
  only:
    - master
sudo: required
services:
  - docker

before_install:
  - docker pull quboleinc/hadoop_mvn_thrift

script: docker run -it --rm -v "$PWD":/usr/src/rubix -v "$HOME/.m2":/root/.m2 -w /usr/src/rubix quboleinc/hadoop_mvn_thrift /bin/bash script.sh -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH"