branches:
  only:
    - master
sudo: required
services:
  - docker

before_install:
  - docker pull kvankayala/hadoop_mvn_thrift

script: docker run -it --rm -v "$PWD":/usr/src/rubix -v "$HOME/.m2":/root/.m2 -w /usr/src/rubix kvankayala/hadoop_mvn_thrift /bin/bash script.sh